version: '3.8'

services:
  vllm_service:
    image: vllm/vllm-openai:v0.10.0
    container_name: vllm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes:
      - /mnt/data/huggingface:/root/.cache/huggingface
    restart: always
    #network_mode: host
    # Or you can only publish port 30000
    ports:
      - "8000:8000"
    environment:
      HF_TOKEN: <secret>
    command:
      --model Qwen/Qwen3-4B-Instruct-2507
      --host 0.0.0.0
      --port 8000
      --enable-auto-tool-choice
      --max-model-len 8096
      --tensor-parallel-size 1
      --pipeline-parallel-size 1
      --gpu-memory-utilization 0.5
      --tool-call-parser hermes
#    ulimit67108864
    ipc: host
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
